Add mux function inspired by Hashrocket dotmatrix

diff --git a/zshrc-dorian b/zshrc-dorian
--- a/zshrc-dorian
+++ b/zshrc-dorian
@@ -86,29 +86,34 @@ bindkey "^[b" backward-word
 
 bindkey '^r' history-incremental-search-backward
 
-# function zle-line-init zle-keymap-select {
-#     VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
-#     RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_custom_status) $EPS1"
-#     zle reset-prompt
-# }
-
-# zle -N zle-line-init
-# zle -N zle-keymap-select
 export KEYTIMEOUT=1
 
-# Always TMUX ----------------------------
-# if `command -v tmux >/dev/null`; then
-#   _not_inside_tmux() { [[ -z "$TMUX" ]] }
-#
-#   ensure_tmux_is_running() {
-#     if _not_inside_tmux; then
-#       tat
-#     fi
-#   }
-#
-#   ensure_tmux_is_running
-# fi
-# ----------------------------------------
+function mux() {
+  if [ -n "$TMUX" ]; then
+    echo "ERROR: You're already in a tmux session. Nesting tmux sessions is a bad idea." >&2
+    return 1
+  fi
+
+  if [ -z "$1" ]; then;
+    session_name="$(basename `pwd` | sed -e 's/\./-/g')"
+  else
+    session_name=$1
+  fi
+
+  if ! $(tmux has-session -t $name &>/dev/null); then
+    echo "creating session $session_name"
+    # tmux new-session -s $session_name -n 'main'
+    cols="$(tput cols)"
+    tmux new-session -d -n 'code' -s $session_name -x${cols-150} -y50 'reattach-to-user-namespace -l zsh'
+
+    source tmux split-window -t $session_name:0 \; \
+      new-window -a -d -n 'server' -t $session_name:0 \; \
+      select-layout -t $session_name main-vertical &>/dev/null \; \
+      send-keys -t $session_name:0.1 'vim .' C-m
+  fi
+
+  exec tmux attach-session -t $session_name
+}
 
 # add rbenv
 export PATH="$HOME/.rbenv/bin:$PATH"
